import type { ProjectData } from '@/types/circuit';

export const DEMO_PROJECTS: ProjectData[] = [
  {
    id: 'demo-direct-motor',
    projectName: 'Demo: Direkte Motorsteuerung',
    projectType: 'Steuerstromkreis',
    creatorName: 'Demo',
    createdAt: new Date('2023-01-01T00:00:00Z'),
    lastModified: new Date('2023-01-01T00:00:00Z'),
    components: [
      {
        id: 'c1',
        type: '24V',
        firebaseComponentId: 'spannung_24v',
        parentId: null,
        x: 50,
        y: 60,
        label: '+24V',
        scale: 1,
        width: null,
        height: null,
      },
      {
        id: 'c2',
        type: '0V',
        firebaseComponentId: 'masse_0v',
        parentId: null,
        x: 450,
        y: 170,
        label: '0V',
        scale: 1,
        width: null,
        height: null,
      },
      {
        id: 'c3',
        type: 'Schließer',
        firebaseComponentId: 'taster_schliesser_steuerung',
        parentId: null,
        x: 200,
        y: 70,
        label: 'S1',
        displayPinLabels: { '13': '13', '14': '14' },
        scale: 1,
        width: null,
        height: null,
      },
      {
        id: 'c4',
        type: 'SchuetzSpule',
        firebaseComponentId: 'schuetzspule',
        parentId: null,
        x: 350,
        y: 125,
        label: 'K1',
        displayPinLabels: { 'A1': 'A1', 'A2': 'A2' },
        scale: 1,
        width: null,
        height: null,
      },
      {
        id: 'c5',
        type: 'Schließer',
        firebaseComponentId: 'taster_schliesser_steuerung',
        parentId: null,
        x: 250,
        y: 70,
        label: 'K1',
        displayPinLabels: { '13': '13', '14': '14' },
        scale: 1,
        width: null,
        height: null,
      },
      {
        id: 'c6',
        type: 'Lampe',
        firebaseComponentId: 'lampe_steuerung',
        parentId: null,
        x: 400,
        y: 117.5,
        label: 'P1',
        displayPinLabels: { 'X1': 'X1', 'X2': 'X2' },
        scale: 1,
        width: null,
        height: null,
      },
    ],
    connections: [
      {
        id: 'conn1',
        startComponentId: 'c1',
        startPinName: 'rail@100',
        endComponentId: 'c3',
        endPinName: '13',
      },
      {
        id: 'conn2',
        startComponentId: 'c3',
        startPinName: '14',
        endComponentId: 'c4',
        endPinName: 'A1',
      },
      {
        id: 'conn3',
        startComponentId: 'c4',
        startPinName: 'A2',
        endComponentId: 'c2',
        endPinName: 'rail@0',
      },
      {
        id: 'conn4',
        startComponentId: 'c1',
        startPinName: 'rail@90',
        endComponentId: 'c5',
        endPinName: '13',
      },
      {
        id: 'conn5',
        startComponentId: 'c5',
        startPinName: '14',
        endComponentId: 'c6',
        endPinName: 'X1',
      },
      {
        id: 'conn6',
        startComponentId: 'c6',
        startPinName: 'X2',
        endComponentId: 'c2',
        endPinName: 'rail@50',
      },
    ],
  },
];

export const getDemoProject = (id: string): ProjectData | undefined => {
  return DEMO_PROJECTS.find(p => p.id === id);
};
