
import type { PaletteComponentFirebaseData } from '@/types/circuit';
import { COMPONENT_DEFINITIONS } from './component-definitions';

export const MOCK_PALETTE_COMPONENTS: PaletteComponentFirebaseData[] = [
  {
    id: 'spannung_24v',
    name: '24V DC Quelle',
    type: '24V',
    abbreviation: 'G',
    defaultLabelPrefix: '+24V',
    category: 'Energieversorgung',
    description: 'Gleichspannungsquelle für den Steuerstromkreis.',
    hasToggleState: false,
    hasEditablePins: false,
    initialPinLabels: { 'out': '' },
    resizable: false,
    defaultSize: { width: COMPONENT_DEFINITIONS['24V'].width, height: COMPONENT_DEFINITIONS['24V'].height },
  },
  {
    id: 'masse_0v',
    name: '0V DC Masse',
    type: '0V',
    abbreviation: 'G',
    defaultLabelPrefix: '0V',
    category: 'Energieversorgung',
    description: 'Bezugspotential für den Steuerstromkreis.',
    hasToggleState: false,
    hasEditablePins: false,
    initialPinLabels: { 'in': '' },
    resizable: false,
    defaultSize: { width: COMPONENT_DEFINITIONS['0V'].width, height: COMPONENT_DEFINITIONS['0V'].height },
  },
  {
    id: 'taster_schliesser',
    name: 'Taster (Schließer NO)',
    type: 'Schließer',
    abbreviation: 'S',
    defaultLabelPrefix: 'S',
    category: 'Befehlsgeräte',
    description: 'Schließt einen Kontakt, solange er betätigt wird. (Normally Open)',
    hasToggleState: true,
    hasEditablePins: true,
    initialPinLabels: { '13': '13', '14': '14' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Schließer'].width, height: COMPONENT_DEFINITIONS['Schließer'].height },
    minScale: 0.5,
    maxScale: 2.0,
    scaleStep: 0.1,
  },
  {
    id: 'taster_oeffner',
    name: 'Taster (Öffner NC)',
    type: 'Öffner',
    abbreviation: 'S',
    defaultLabelPrefix: 'S',
    category: 'Befehlsgeräte',
    description: 'Öffnet einen Kontakt, solange er betätigt wird. (Normally Closed)',
    hasToggleState: true,
    hasEditablePins: true,
    initialPinLabels: { '11': '11', '12': '12' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Öffner'].width, height: COMPONENT_DEFINITIONS['Öffner'].height },
    minScale: 0.5,
    maxScale: 2.0,
    scaleStep: 0.1,
  },
  {
    id: 'not_aus_taster',
    name: 'Not-Aus-Taster',
    type: 'Öffner', 
    paletteIconType: 'NotAusTaster', 
    abbreviation: 'S',
    defaultLabelPrefix: 'SQ',
    category: 'Befehlsgeräte',
    description: 'Sicherheitsrelevanter Öffner mit mechanischer Verriegelung. Zur Notabschaltung.',
    hasToggleState: true, 
    hasEditablePins: true,
    initialPinLabels: { '11': '11', '12': '12' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Öffner'].width, height: COMPONENT_DEFINITIONS['Öffner'].height }, // Uses Öffner's base size
    minScale: 0.8, // Not-Aus usually not scaled much
    maxScale: 1.5,
    scaleStep: 0.1,
  },
  {
    id: 'schuetzspule',
    name: 'Schützspule',
    type: 'SchuetzSpule',
    abbreviation: 'K',
    defaultLabelPrefix: 'K',
    category: 'Speichernde / Verarbeitende',
    description: 'Elektromagnetische Spule zur Ansteuerung von Leistungskontakten.',
    hasToggleState: false,
    hasEditablePins: true,
    initialPinLabels: { 'A1': 'A1', 'A2': 'A2' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['SchuetzSpule'].width, height: COMPONENT_DEFINITIONS['SchuetzSpule'].height },
    minScale: 0.7,
    maxScale: 1.8,
    scaleStep: 0.1,
  },
  {
    id: 'zeitrelais_ein',
    name: 'Zeitrelais (Einschaltverzögert)',
    type: 'ZeitRelaisEin',
    abbreviation: 'KT',
    defaultLabelPrefix: 'KT',
    category: 'Speichernde / Verarbeitende',
    description: 'Kontakt schließt/öffnet nach einer einstellbaren Verzögerungszeit.',
    hasToggleState: false, 
    hasEditablePins: true, 
    initialPinLabels: { 'A1': 'A1', 'A2': 'A2', 'T': '5s' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['ZeitRelaisEin'].width, height: COMPONENT_DEFINITIONS['ZeitRelaisEin'].height },
    minScale: 0.7,
    maxScale: 1.8,
    scaleStep: 0.1,
  },
  {
    id: 'motor_steuerung', 
    name: 'Motor (Steuerstrom)',
    type: 'Motor', 
    abbreviation: 'M',
    defaultLabelPrefix: 'M',
    category: 'Stellglieder',
    description: 'Stellglied, das einen Motor im Hauptstromkreis repräsentiert.',
    hasToggleState: false,
    hasEditablePins: true,
    initialPinLabels: { 'A1': 'A1', 'A2': 'A2' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Motor'].width, height: COMPONENT_DEFINITIONS['Motor'].height },
    minScale: 0.5,
    maxScale: 2.5,
    scaleStep: 0.1,
  },
  {
    id: 'lampe',
    name: 'Lampe / Meldeleuchte',
    type: 'Lampe',
    abbreviation: 'H',
    defaultLabelPrefix: 'H',
    category: 'Stellglieder',
    description: 'Zeigt optisch einen Zustand an.',
    hasToggleState: false,
    hasEditablePins: true,
    initialPinLabels: { 'X1': 'X1', 'X2': 'X2' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Lampe'].width, height: COMPONENT_DEFINITIONS['Lampe'].height },
    minScale: 0.5,
    maxScale: 2.0,
    scaleStep: 0.1,
  },
];

// Helper to find a palette component by its firebase ID
export const getPaletteComponentById = (id: string | undefined): PaletteComponentFirebaseData | undefined => {
  if (!id) return undefined;
  return MOCK_PALETTE_COMPONENTS.find(p => p.id === id);
};
