
import type { PaletteComponentFirebaseData } from '@/types/circuit';
import { COMPONENT_DEFINITIONS } from './component-definitions';

export const MOCK_PALETTE_COMPONENTS: PaletteComponentFirebaseData[] = [
  // Energieversorgung
  {
    id: 'spannung_24v',
    name: '24V DC Quelle',
    type: '24V',
    abbreviation: 'G',
    defaultLabelPrefix: '+24V',
    category: 'Energieversorgung',
    description: 'Gleichspannungsquelle für den Steuerstromkreis.',
    hasToggleState: false,
    hasEditablePins: false,
    initialPinLabels: { 'out': '' },
    resizable: false,
    defaultSize: { width: COMPONENT_DEFINITIONS['24V'].width, height: COMPONENT_DEFINITIONS['24V'].height },
    simulation: {
      interactable: false,
      controlLogic: 'pass_through', // Acts as a source
      controlledBy: 'voltage', // Implicitly provides voltage
      energizePins: ['out'], // This pin provides power
    }
  },
  {
    id: 'masse_0v',
    name: '0V DC Masse',
    type: '0V',
    abbreviation: 'G',
    defaultLabelPrefix: '0V',
    category: 'Energieversorgung',
    description: 'Bezugspotential für den Steuerstromkreis.',
    hasToggleState: false,
    hasEditablePins: false,
    initialPinLabels: { 'in': '' },
    resizable: false,
    defaultSize: { width: COMPONENT_DEFINITIONS['0V'].width, height: COMPONENT_DEFINITIONS['0V'].height },
    simulation: {
      interactable: false,
      controlLogic: 'pass_through', // Acts as a sink
      controlledBy: 'voltage',
    }
  },
  {
    id: 'phase_l1',
    name: 'Phase L1',
    type: 'L1',
    abbreviation: 'L1',
    defaultLabelPrefix: 'L1',
    category: 'Energieversorgung',
    description: 'Außenleiter L1 für Hauptstromkreise.',
    hasToggleState: false,
    hasEditablePins: false,
    initialPinLabels: { 'pin': '' },
    resizable: false,
    defaultSize: { width: COMPONENT_DEFINITIONS['L1'].width, height: COMPONENT_DEFINITIONS['L1'].height },
    voltageType: 'AC_L',
    simulation: {
      interactable: false,
      controlLogic: 'pass_through',
      controlledBy: 'voltage',
    }
  },
  {
    id: 'phase_l2',
    name: 'Phase L2',
    type: 'L2',
    abbreviation: 'L2',
    defaultLabelPrefix: 'L2',
    category: 'Energieversorgung',
    description: 'Außenleiter L2 für Hauptstromkreise.',
    hasToggleState: false,
    hasEditablePins: false,
    initialPinLabels: { 'pin': '' },
    resizable: false,
    defaultSize: { width: COMPONENT_DEFINITIONS['L2'].width, height: COMPONENT_DEFINITIONS['L2'].height },
    voltageType: 'AC_L',
    simulation: {
      interactable: false,
      controlLogic: 'pass_through',
      controlledBy: 'voltage',
    }
  },
  {
    id: 'phase_l3',
    name: 'Phase L3',
    type: 'L3',
    abbreviation: 'L3',
    defaultLabelPrefix: 'L3',
    category: 'Energieversorgung',
    description: 'Außenleiter L3 für Hauptstromkreise.',
    hasToggleState: false,
    hasEditablePins: false,
    initialPinLabels: { 'pin': '' },
    resizable: false,
    defaultSize: { width: COMPONENT_DEFINITIONS['L3'].width, height: COMPONENT_DEFINITIONS['L3'].height },
    voltageType: 'AC_L',
    simulation: {
      interactable: false,
      controlLogic: 'pass_through',
      controlledBy: 'voltage',
    }
  },
  {
    id: 'neutralleiter',
    name: 'Neutralleiter',
    type: 'N',
    abbreviation: 'N',
    defaultLabelPrefix: 'N',
    category: 'Energieversorgung',
    description: 'Neutralleiter für Hauptstromkreise.',
    hasToggleState: false,
    hasEditablePins: false,
    initialPinLabels: { 'pin': '' },
    resizable: false,
    defaultSize: { width: COMPONENT_DEFINITIONS['N'].width, height: COMPONENT_DEFINITIONS['N'].height },
    voltageType: 'NEUTRAL',
    simulation: {
      interactable: false,
      controlLogic: 'pass_through',
      controlledBy: 'voltage',
    }
  },
  {
    id: 'schutzleiter',
    name: 'Schutzleiter',
    type: 'PE',
    abbreviation: 'PE',
    defaultLabelPrefix: 'PE',
    category: 'Energieversorgung',
    description: 'Schutzleiter (PE).',
    hasToggleState: false,
    hasEditablePins: false,
    initialPinLabels: { 'pin': '' },
    resizable: false,
    defaultSize: { width: COMPONENT_DEFINITIONS['PE'].width, height: COMPONENT_DEFINITIONS['PE'].height },
    voltageType: 'PE',
    simulation: {
      interactable: false,
      controlLogic: 'pass_through',
      controlledBy: 'voltage',
    }
  },
  // Befehlsgeräte
  {
    id: 'taster_schliesser_steuerung', // Unique ID for control circuit version
    name: 'Taster (Schließer NO)',
    type: 'Schließer', // Standard type for control circuit
    abbreviation: 'S',
    defaultLabelPrefix: 'S',
    category: 'Befehlsgeräte (Steuerstrom)',
    description: 'Schließt einen Kontakt, solange er betätigt wird. (Normally Open)',
    hasToggleState: true,
    hasEditablePins: true,
    initialPinLabels: { '13': '13', '14': '14' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Schließer'].width, height: COMPONENT_DEFINITIONS['Schließer'].height },
    minScale: 0.5, maxScale: 2.0, scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_press',
      controlledBy: 'user',
      initialContactState: { "13": "open", "14": "open" }, // Assuming default state for simulation
      outputPinStateOnEnergized: { "13": "closed", "14": "closed" }, // When pressed
      outputPinStateOnDeEnergized: { "13": "open", "14": "open" }, // When released
    }
  },
  {
    id: 'taster_oeffner_steuerung', // Unique ID
    name: 'Taster (Öffner NC)',
    type: 'Öffner', // Standard type
    abbreviation: 'S',
    defaultLabelPrefix: 'S',
    category: 'Befehlsgeräte (Steuerstrom)',
    description: 'Öffnet einen Kontakt, solange er betätigt wird. (Normally Closed)',
    hasToggleState: true,
    hasEditablePins: true,
    initialPinLabels: { '11': '11', '12': '12' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Öffner'].width, height: COMPONENT_DEFINITIONS['Öffner'].height },
    minScale: 0.5, maxScale: 2.0, scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_press',
      controlledBy: 'user',
      initialContactState: { "11": "closed", "12": "closed" },
      outputPinStateOnEnergized: { "11": "open", "12": "open" }, // When pressed
      outputPinStateOnDeEnergized: { "11": "closed", "12": "closed" }, // When released
    }
  },
  {
    id: 'not_aus_taster_steuerung', // Unique ID
    name: 'Not-Aus-Taster',
    type: 'Öffner',
    paletteIconType: 'NotAusTaster',
    abbreviation: 'S',
    defaultLabelPrefix: 'S',
    category: 'Befehlsgeräte (Steuerstrom)',
    description: 'Sicherheitsrelevanter Öffner mit mechanischer Verriegelung.',
    hasToggleState: true,
    hasEditablePins: true,
    initialPinLabels: { '11': '11', '12': '12' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Öffner'].width, height: COMPONENT_DEFINITIONS['Öffner'].height },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_click', // Stays pressed until manually reset (simulated by toggle)
      controlledBy: 'user',
      initialContactState: { "11": "closed", "12": "closed" },
      outputPinStateOnEnergized: { "11": "open", "12": "open" }, // When activated
      outputPinStateOnDeEnergized: { "11": "closed", "12": "closed" }, // When reset
    }
  },
  // Speichernde / Verarbeitende
  {
    id: 'schuetzspule',
    name: 'Schützspule',
    type: 'SchuetzSpule',
    abbreviation: 'K',
    defaultLabelPrefix: 'K',
    category: 'Speichernde / Verarbeitende (Steuerstrom)',
    description: 'Elektromagnetische Spule zur Ansteuerung von Kontakten.',
    hasToggleState: false,
    hasEditablePins: true,
    initialPinLabels: { 'A1': 'A1', 'A2': 'A2' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['SchuetzSpule'].width, height: COMPONENT_DEFINITIONS['SchuetzSpule'].height },
    minScale: 0.7, maxScale: 1.8, scaleStep: 0.1,
    simulation: {
      interactable: false,
      controlLogic: 'energize_coil',
      controlledBy: 'voltage',
      energizePins: ['A1', 'A2'],
      affectingLabel: true,
    }
  },
  {
    id: 'kontakt_schliesser',
    name: 'Schließer',
    type: 'Schließer',
    abbreviation: 'K',
    defaultLabelPrefix: 'K',
    category: 'Speichernde / Verarbeitende (Steuerstrom)',
    description: 'Kontakt, der von einer Spule betätigt wird (NO).',
    hasToggleState: false,
    hasEditablePins: true,
    initialPinLabels: { '13': '13', '14': '14' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Schließer'].width, height: COMPONENT_DEFINITIONS['Schließer'].height },
    minScale: 0.5, maxScale: 2.0, scaleStep: 0.1,
    simulation: {
      interactable: false,
      controlLogic: 'fixed_open',
      controlledBy: 'label_match',
      initialContactState: { '13': 'open', '14': 'open' },
      outputPinStateOnEnergized: { '13': 'closed', '14': 'closed' },
      outputPinStateOnDeEnergized: { '13': 'open', '14': 'open' },
    }
  },
  {
    id: 'kontakt_oeffner',
    name: 'Öffner',
    type: 'Öffner',
    abbreviation: 'K',
    defaultLabelPrefix: 'K',
    category: 'Speichernde / Verarbeitende (Steuerstrom)',
    description: 'Kontakt, der von einer Spule betätigt wird (NC).',
    hasToggleState: false,
    hasEditablePins: true,
    initialPinLabels: { '11': '11', '12': '12' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Öffner'].width, height: COMPONENT_DEFINITIONS['Öffner'].height },
    minScale: 0.5, maxScale: 2.0, scaleStep: 0.1,
    simulation: {
      interactable: false,
      controlLogic: 'fixed_closed',
      controlledBy: 'label_match',
      initialContactState: { '11': 'closed', '12': 'closed' },
      outputPinStateOnEnergized: { '11': 'open', '12': 'open' },
      outputPinStateOnDeEnergized: { '11': 'closed', '12': 'closed' },
    }
  },
  {
    id: 'zeitrelais_ein',
    name: 'Zeitrelais (Einschaltverzögert)',
    type: 'ZeitRelaisEin',
    abbreviation: 'KT',
    defaultLabelPrefix: 'KT',
    category: 'Speichernde / Verarbeitende (Steuerstrom)',
    description: 'Kontakt schließt/öffnet nach Verzögerung.',
    hasToggleState: false,
    hasEditablePins: true,
    initialPinLabels: { 'A1': 'A1', 'A2': 'A2', 'T': '5s' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['ZeitRelaisEin'].width, height: COMPONENT_DEFINITIONS['ZeitRelaisEin'].height },
    minScale: 0.7, maxScale: 1.8, scaleStep: 0.1,
    simulation: {
      interactable: false,
      controlLogic: 'timer_on_delay',
      controlledBy: 'voltage',
      energizePins: ['A1', 'A2'],
      affectingLabel: true,
      timerDurationMs: 5000, // Default, could be parsed from 'T' label
      outputPinStateOnEnergized: {}, // Logic for contact state change after timer
      outputPinStateOnDeEnergized: {},
    }
  },
  // Stellglieder
  {
    id: 'motor_steuerung',
    name: 'Motor (Steuerstrom)',
    type: 'Motor',
    abbreviation: 'M',
    defaultLabelPrefix: 'M',
    category: 'Stellglieder (Steuerstrom)',
    description: 'Stellglied, das einen Motor repräsentiert.',
    hasToggleState: false,
    hasEditablePins: true,
    initialPinLabels: { 'A1': 'A1', 'A2': 'A2' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Motor'].width, height: COMPONENT_DEFINITIONS['Motor'].height },
    minScale: 0.5, maxScale: 2.5, scaleStep: 0.1,
    simulation: {
      interactable: false,
      controlLogic: 'visualize_energized',
      controlledBy: 'voltage',
      energizePins: ['A1', 'A2'],
    }
  },
  {
    id: 'lampe_steuerung',
    name: 'Lampe / Meldeleuchte',
    type: 'Lampe',
    abbreviation: 'H',
    defaultLabelPrefix: 'H',
    category: 'Stellglieder (Steuerstrom)',
    description: 'Zeigt optisch einen Zustand an.',
    hasToggleState: false,
    hasEditablePins: true,
    initialPinLabels: { 'X1': 'X1', 'X2': 'X2' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Lampe'].width, height: COMPONENT_DEFINITIONS['Lampe'].height },
    minScale: 0.5, maxScale: 2.0, scaleStep: 0.1,
    simulation: {
      interactable: false,
      controlLogic: 'visualize_energized',
      controlledBy: 'voltage',
    energizePins: ['X1', 'X2'],
    }
  },

  // Hauptstromkreis
  {
    id: 'motorschutzschalter',
    name: 'Motorschutzschalter',
    type: 'Motorschutzschalter',
    abbreviation: 'Q',
    defaultLabelPrefix: 'Q',
    category: 'Hauptstromkreis',
    description: 'Schützt Motoren vor Überlast und Kurzschluss.',
    hasToggleState: true,
    hasEditablePins: true,
    initialPinLabels: { 'L1': 'L1', 'T1': 'T1', 'L2': 'L2', 'T2': 'T2', 'L3': 'L3', 'T3': 'T3' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Motorschutzschalter'].width, height: COMPONENT_DEFINITIONS['Motorschutzschalter'].height },
    minScale: 0.7,
    maxScale: 1.8,
    scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_click',
      controlledBy: 'user',
      initialContactState: { 'L1': 'closed', 'T1': 'closed', 'L2': 'closed', 'T2': 'closed', 'L3': 'closed', 'T3': 'closed' },
      outputPinStateOnEnergized: { 'L1': 'open', 'T1': 'open', 'L2': 'open', 'T2': 'open', 'L3': 'open', 'T3': 'open' },
      outputPinStateOnDeEnergized: { 'L1': 'closed', 'T1': 'closed', 'L2': 'closed', 'T2': 'closed', 'L3': 'closed', 'T3': 'closed' }
    }
  },
  {
    id: 'sicherung',
    name: 'Sicherung',
    type: 'Sicherung',
    abbreviation: 'F',
    defaultLabelPrefix: 'F',
    category: 'Hauptstromkreis',
    description: 'Schmelzsicherung zum Leitungsschutz.',
    hasToggleState: true,
    hasEditablePins: false,
    initialPinLabels: { 'in': '', 'out': '' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Sicherung'].width, height: COMPONENT_DEFINITIONS['Sicherung'].height },
    minScale: 0.7,
    maxScale: 1.5,
    scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_click',
      controlledBy: 'user',
      initialContactState: { 'in': 'closed', 'out': 'closed' },
      outputPinStateOnEnergized: { 'in': 'open', 'out': 'open' },
      outputPinStateOnDeEnergized: { 'in': 'closed', 'out': 'closed' }
    }
  },

  // Installationselemente
  {
    id: 'abzweigdose_install',
    name: 'Abzweigdose',
    type: 'Abzweigdose',
    abbreviation: 'X',
    defaultLabelPrefix: 'X',
    category: 'Installationselemente',
    description: 'Verteilerdose für Leitungen.',
    hasToggleState: false,
    hasEditablePins: false, // Pins are fixed
    initialPinLabels: { 'N': 'N', 'E': 'E', 'S': 'S', 'W': 'W' }, // Example pins
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Abzweigdose']?.width || 50, height: COMPONENT_DEFINITIONS['Abzweigdose']?.height || 50 },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: false,
      controlLogic: 'pass_through',
      controlledBy: 'voltage',
    }
  },
  {
    id: 'abzweigdose_rect',
    name: 'Abzweigdose (Rechteck)',
    type: 'AbzweigdoseRect',
    abbreviation: 'X',
    defaultLabelPrefix: 'X',
    category: 'Installationselemente',
    description: 'Rechteckige Abzweigdose zur Verdrahtung.',
    hasToggleState: false,
    hasEditablePins: false,
    initialPinLabels: { 'N': 'N', 'E': 'E', 'S': 'S', 'W': 'W' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['AbzweigdoseRect']?.width || 50, height: COMPONENT_DEFINITIONS['AbzweigdoseRect']?.height || 40 },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: false,
      controlLogic: 'pass_through',
      controlledBy: 'voltage',
    }
  },
  {
    id: 'taster_schliesser_install',
    name: 'Taster (Installation)',
    type: 'SchliesserInstallation',
    abbreviation: 'S',
    defaultLabelPrefix: 'S',
    category: 'Installationselemente',
    description: 'Taster für Installationspläne.',
    hasToggleState: true,
    hasEditablePins: true, // Usually fixed in installation symbols but can be kept for consistency
    initialPinLabels: { 'L': 'L', 'Out': 'Out' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['SchliesserInstallation']?.width || 30, height: COMPONENT_DEFINITIONS['SchliesserInstallation']?.height || 30 },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_press',
      controlledBy: 'user',
      initialContactState: { "L": "open", "Out": "open" }, // Assuming L is input, Out is output
      outputPinStateOnEnergized: { "L": "closed", "Out": "closed" },
      outputPinStateOnDeEnergized: { "L": "open", "Out": "open" },
    }
  },
  {
    id: 'ausschalter_install',
    name: 'Ausschalter',
    type: 'Ausschalter',
    abbreviation: 'A',
    defaultLabelPrefix: 'A',
    category: 'Installationselemente',
    description: 'Einpoliger Ausschalter mit Rastmechanik.',
    hasToggleState: true,
    hasEditablePins: false,
    initialPinLabels: { 'L': 'L', 'Out': 'Out' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Ausschalter']?.width || 30, height: COMPONENT_DEFINITIONS['Ausschalter']?.height || 30 },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_click',
      controlledBy: 'user',
      initialContactState: { 'L': 'open', 'Out': 'open' },
      outputPinStateOnEnergized: { 'L': 'closed', 'Out': 'closed' },
      outputPinStateOnDeEnergized: { 'L': 'open', 'Out': 'open' },
    }
  },
  {
    id: 'lampe_install',
    name: 'Leuchte (Installation)',
    type: 'LampeInstallation',
    abbreviation: 'E',
    defaultLabelPrefix: 'E',
    category: 'Installationselemente',
    description: 'Leuchtensymbol für Installationspläne.',
    hasToggleState: false,
    hasEditablePins: true, // Usually fixed
    initialPinLabels: { 'L': 'L', 'N': 'N' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['LampeInstallation']?.width || 30, height: COMPONENT_DEFINITIONS['LampeInstallation']?.height || 30 },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: false,
      controlLogic: 'visualize_energized',
      controlledBy: 'voltage',
    energizePins: ['L', 'N'],
    }
  },
  {
    id: 'fi_schutzschalter',
    name: 'Fehlerstromschutzschalter',
    type: 'Fehlerstromschutzschalter',
    abbreviation: 'FI',
    defaultLabelPrefix: 'FI',
    category: 'Installationselemente',
    description: 'Unterbricht alle Leiter bei Fehlerströmen.',
    hasToggleState: true,
    hasEditablePins: true,
    initialPinLabels: { 'L1': 'L1', "L1out": "L1'", 'L2': 'L2', "L2out": "L2'", 'L3': 'L3', "L3out": "L3'", 'N': 'N', "Nout": "N'" },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Fehlerstromschutzschalter'].width, height: COMPONENT_DEFINITIONS['Fehlerstromschutzschalter'].height },
    minScale: 0.7,
    maxScale: 1.5,
    scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_click',
      controlledBy: 'user',
      initialContactState: { 'L1': 'closed', 'L1out': 'closed', 'L2': 'closed', 'L2out': 'closed', 'L3': 'closed', 'L3out': 'closed', 'N': 'closed', 'Nout': 'closed' },
      outputPinStateOnEnergized: { 'L1': 'open', 'L1out': 'open', 'L2': 'open', 'L2out': 'open', 'L3': 'open', 'L3out': 'open', 'N': 'open', 'Nout': 'open' },
      outputPinStateOnDeEnergized: { 'L1': 'closed', 'L1out': 'closed', 'L2': 'closed', 'L2out': 'closed', 'L3': 'closed', 'L3out': 'closed', 'N': 'closed', 'Nout': 'closed' }
    }
  },
  {
    id: 'steckdose_install',
    name: 'Steckdose',
    type: 'Steckdose',
    abbreviation: 'SD',
    defaultLabelPrefix: 'SD',
    category: 'Installationselemente',
    description: 'Schutzkontaktsteckdose.',
    hasToggleState: false,
    hasEditablePins: false,
    initialPinLabels: { 'L': 'L', 'N': 'N', 'PE': 'PE' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Steckdose']?.width || 30, height: COMPONENT_DEFINITIONS['Steckdose']?.height || 30 },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: false,
      controlLogic: 'pass_through',
      controlledBy: 'voltage',
    }
  },
  {
    id: 'wechselschalter_install',
    name: 'Wechselschalter',
    type: 'Wechselschalter',
    abbreviation: 'W',
    defaultLabelPrefix: 'W',
    category: 'Installationselemente',
    description: 'Schalter mit zwei Ausgängen.',
    hasToggleState: true,
    hasEditablePins: false,
    initialPinLabels: { 'L': 'L', 'Ausgang1': '1', 'Ausgang2': '2' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Wechselschalter']?.width || 30, height: COMPONENT_DEFINITIONS['Wechselschalter']?.height || 30 },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_click',
      controlledBy: 'user',
      initialContactState: { 'L': 'closed', 'Ausgang1': 'closed', 'Ausgang2': 'open' },
      outputPinStateOnEnergized: { 'L': 'closed', 'Ausgang1': 'open', 'Ausgang2': 'closed' },
    outputPinStateOnDeEnergized: { 'L': 'closed', 'Ausgang1': 'closed', 'Ausgang2': 'open' },
    }
  },
  {
    id: 'serienschalter_install',
    name: 'Serienschalter',
    type: 'Serienschalter',
    abbreviation: 'S',
    defaultLabelPrefix: 'S',
    category: 'Installationselemente',
    description: 'Doppelschalter mit gemeinsamem Eingang.',
    hasToggleState: true,
    hasEditablePins: false,
    initialPinLabels: { 'L': 'L', '1': '1', '2': '2' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Serienschalter']?.width || 40, height: COMPONENT_DEFINITIONS['Serienschalter']?.height || 30 },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_click',
      controlledBy: 'user',
      initialContactState: { '1': 'open', '2': 'open' },
      outputPinStateOnEnergized: { '1': 'closed', '2': 'closed' },
      outputPinStateOnDeEnergized: { '1': 'open', '2': 'open' },
    }
  },
  {
    id: 'kreuzschalter_install',
    name: 'Kreuzschalter',
    type: 'Kreuzschalter',
    abbreviation: 'K',
    defaultLabelPrefix: 'K',
    category: 'Installationselemente',
    description: 'Schalter, der Leitungen kreuzt oder gerade verbindet.',
    hasToggleState: true,
    hasEditablePins: false,
    initialPinLabels: { '1': '1', '2': '2', '3': '3', '4': '4' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Kreuzschalter']?.width || 40, height: COMPONENT_DEFINITIONS['Kreuzschalter']?.height || 30 },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_click',
      controlledBy: 'user',
      initialContactState: { 'cross': 'open' },
      outputPinStateOnEnergized: { 'cross': 'closed' },
      outputPinStateOnDeEnergized: { 'cross': 'open' },
    }
  },
  {
    id: 'schalter_steckdose_kombi',
    name: 'Kombination Schalter/Steckdose',
    type: 'SchalterSteckdoseKombi',
    abbreviation: 'KS',
    defaultLabelPrefix: 'KS',
    category: 'Installationselemente',
    description: 'Schalter mit integrierter Schutzkontaktsteckdose.',
    hasToggleState: true,
    hasEditablePins: false,
    initialPinLabels: { 'SchalterL': 'L', 'SchaltOut': '1', 'L': 'L', 'N': 'N', 'PE': 'PE' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['SchalterSteckdoseKombi']?.width || 30, height: COMPONENT_DEFINITIONS['SchalterSteckdoseKombi']?.height || 60 },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_click',
      controlledBy: 'user',
      initialContactState: { 'SchaltOut': 'open' },
      outputPinStateOnEnergized: { 'SchaltOut': 'closed' },
      outputPinStateOnDeEnergized: { 'SchaltOut': 'open' },
    }
  },
  {
    id: 'taster_kontrolllicht',
    name: 'Taster mit Kontrolllicht',
    type: 'TasterKontrolllicht',
    abbreviation: 'TK',
    defaultLabelPrefix: 'TK',
    category: 'Installationselemente',
    description: 'Taster mit integriertem Kontrolllicht.',
    hasToggleState: true,
    hasEditablePins: false,
    initialPinLabels: { 'L': 'L', 'Out': 'Out', 'N': 'N' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['TasterKontrolllicht']?.width || 30, height: COMPONENT_DEFINITIONS['TasterKontrolllicht']?.height || 40 },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_press',
      controlledBy: 'user',
      initialContactState: { 'Out': 'open' },
      outputPinStateOnEnergized: { 'Out': 'closed' },
      outputPinStateOnDeEnergized: { 'Out': 'open' },
    }
  },
  {
    id: 'grenztaster_sensor',
    name: 'Grenztaster',
    type: 'Grenztaster',
    abbreviation: 'G',
    defaultLabelPrefix: 'G',
    category: 'Sensoren',
    description: 'Mechanischer Grenztaster als Sensor.',
    hasToggleState: true,
    hasEditablePins: false,
    initialPinLabels: { 'in': 'in', 'out': 'out' },
    resizable: true,
    defaultSize: { width: COMPONENT_DEFINITIONS['Grenztaster']?.width || 30, height: COMPONENT_DEFINITIONS['Grenztaster']?.height || 30 },
    minScale: 0.8, maxScale: 1.5, scaleStep: 0.1,
    simulation: {
      interactable: true,
      controlLogic: 'toggle_on_press',
      controlledBy: 'user',
      initialContactState: { 'in': 'open', 'out': 'open' },
      outputPinStateOnEnergized: { 'in': 'closed', 'out': 'closed' },
      outputPinStateOnDeEnergized: { 'in': 'open', 'out': 'open' },
    }
  },
];

export const getPaletteComponentById = (id: string | undefined): PaletteComponentFirebaseData | undefined => {
  if (!id) return undefined;
  return MOCK_PALETTE_COMPONENTS.find(p => p.id === id);
};
